root: true

extends:
  - 'plugin:jasmine/recommended'
  - airbnb-base

parser: babel-eslint

env:
  browser: true
  es6: true
  node: true
  jasmine: true

globals:
  expectAsync: true

plugins:
  - jsdoc
  - jasmine

rules:
  no-console: 0  # This project purposely uses console.
  jasmine/no-spec-dupes:
    - 1
    - 'branch'
