language: node_js

node_js:
  - "8"

env:
  global:
  - ENCRYPTION_LABEL: "61f3e155fadb"
  - COMMIT_AUTHOR_EMAIL: "support@itslanguage.nl"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_deploy:
  - yarn run build
  - cd build
deploy:
  - provider: script
    skip_cleanup: true
    script: ./internals/scripts/gh-pages.sh
    # safelist, only build on master or
    # branches (e.g. tags!) that have the
    # vX.X.X format (v.3.0.0)
    on:
      branch:
        - master
        - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

  - provider: npm
    skip_cleanup: true
    email: "travis-ci@itslanguage.nl"
    api_key:
      secure: "j1BaEcsvaqTi28BK8GNz7c0nQY60eWdexpUnHVHDzR5TPNrf0I/uJ+3OXKgc5lvnHqNPsKH25w0fpyXIM0rbOw3WxNMlEEpQbgZVKdufCUX5XK5riZObuQh8pnpzhluCsfaZKJh7NFSFtpyO18cz27E/wZVujF6Xe+DLEM/UVwc70TH2A9wSlqAjFiBEhO1JUhNnxZKBmVSUYzI+CWtukE2ihRm7jLNcn+NtVlb0QnHd1JehtaeUj4mNV6IcFHy1N4STfX4Y+fMUQeXyO1ZsmrDy3YsTG8tsSwTZdqjqNkNJlq9fK8+6/+ZRN2NmXelreGiBaNJsskdYVZBQJN02dOXkjyFQ2BmYERY9hbaJYDJbKzgIvIF6YWEddPjSMO8hJOEtlWQArwgxZ0CrWG6MRl8HV/ah+e7Zj1h9iQUj+H+eMmLF8F2D9e3BlW5x36qAYXbFii9I5MYLbQOehmzX2osONeqFQQTiNb4qeZKeLxY7RzU+2fnBv8s3y+gRmh3aytuWkpppLDVI8+erZDisytbOR0Au7UCqQPdGTEdiKNv19sHA33/PseEp3bgR1QsPDz70jfWcD2nWmg94kRBKa+3sVusYcOR12h+baYAS1oD4+/fJ6IPWj4vrGn8wO9AofKgGCny1G+/QVv6X4XF9P5cdfywVOR53089Z/CCoTZ8="
    on:
      tags: true

