language: node_js

node_js:
  - "8"

env:
  global:
  - ENCRYPTION_LABEL: "61f3e155fadb"
  - COMMIT_AUTHOR_EMAIL: "support@itslanguage.nl"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_deploy:
  - yarn run build
deploy:
  provider: script
  skip_cleanup: true
  script: ./internals/scripts/gh-pages.sh
  # safelist, only build on master or
  # branches (e.g. tags!) that have the
  # vX.X.X format (v.3.0.0)
  branches:
    only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
