sudo: required
language: node_js

node_js:
  - '8'

env:
  global:
  - COMMIT_AUTHOR_NAME: ITSLanguage Bot
  - COMMIT_AUTHOR_EMAIL: its-bot@itslanguage.nl

addons:
  chrome: stable

before_install:
  # Install latest yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s --
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Setup path to Chrome so Karma can find it
  - export CHROME_BIN=google-chrome-stable

after_success:
  # Failing will "fail" the build
  # doing this step in before_deploy
  # will not.
  - yarn run build
  # We want to be in the build directory for
  # all steps that follow
  - cd build
  # Make sure our script is executable
  - chmod +x $TRAVIS_BUILD_DIR/internals/scripts/gh-pages.sh

deploy:
  # Deploy to GitHub pages with our Bot user.
  # Runs when a tag is made available.
  - provider: script
    skip_cleanup: true
    script: "$TRAVIS_BUILD_DIR/internals/scripts/gh-pages.sh"
    on:
      branch: master
      tags: true

  # Deploy to GitHub pages with our Bot user.
  # It seems that it is not possible to specify both "on"
  # arguments. Runs when master get's an update.
  - provider: script
    skip_cleanup: true
    script: "$TRAVIS_BUILD_DIR/internals/scripts/gh-pages.sh"
    on:
      branch: master

  - provider: npm
    skip_cleanup: true
    email: its-bot@itslanguage.nl
    api_key:
      secure: j1BaEcsvaqTi28BK8GNz7c0nQY60eWdexpUnHVHDzR5TPNrf0I/uJ+3OXKgc5lvnHqNPsKH25w0fpyXIM0rbOw3WxNMlEEpQbgZVKdufCUX5XK5riZObuQh8pnpzhluCsfaZKJh7NFSFtpyO18cz27E/wZVujF6Xe+DLEM/UVwc70TH2A9wSlqAjFiBEhO1JUhNnxZKBmVSUYzI+CWtukE2ihRm7jLNcn+NtVlb0QnHd1JehtaeUj4mNV6IcFHy1N4STfX4Y+fMUQeXyO1ZsmrDy3YsTG8tsSwTZdqjqNkNJlq9fK8+6/+ZRN2NmXelreGiBaNJsskdYVZBQJN02dOXkjyFQ2BmYERY9hbaJYDJbKzgIvIF6YWEddPjSMO8hJOEtlWQArwgxZ0CrWG6MRl8HV/ah+e7Zj1h9iQUj+H+eMmLF8F2D9e3BlW5x36qAYXbFii9I5MYLbQOehmzX2osONeqFQQTiNb4qeZKeLxY7RzU+2fnBv8s3y+gRmh3aytuWkpppLDVI8+erZDisytbOR0Au7UCqQPdGTEdiKNv19sHA33/PseEp3bgR1QsPDz70jfWcD2nWmg94kRBKa+3sVusYcOR12h+baYAS1oD4+/fJ6IPWj4vrGn8wO9AofKgGCny1G+/QVv6X4XF9P5cdfywVOR53089Z/CCoTZ8=
    on:
      tags: true

notifications:
  slack:
    secure: h2/webRUw7XjVCWPma3ck+CJKMr5/0jj2A4zsk+Xm83dR8FOSiubWZP6I/0w6GapwcAWfAKPzLbZgPA0RHK5lOUqXyEMqJjeD6Srw1acZ7Ir0lnkC2/77+925Azhc7ZdqR2gZGvtMQ18UZ1u9St4+Gq6PGbZiJ+WY3QM8+U/OPjqpVcdcaQG1EuQrkKZyafTMeEO0zwkBnOyW0rzFKwN2kT8aGfXKvd814cvJv+H9FO0k/YZPDXxmS7nRdcnF8Hbg7x09nBa9Y9Q9vTNhBcmclUAqAbNcghD2hEYOPkRKm5hIOyzDt66vhCvDKZD3zHH/opp1sh2ClOB5Cqh7cc3MiUS/PAyAqaO+++1bfmv09SvHIydWI1jRyrxPJxtinA7WLjedkY2g7l+3cJ+WcwGgOLW+5IlSMbjTQI92TPv6aeWw/DzyAzjRGEP25Q7hFSmq2mZjCrTcI+Bm5ZZuIlvemClri4MT8rJsPSbuMzgare1TMM1WZK8oybTPkCHwDscg+hn6ZvoVWScxk/4E1dt1P0qAkXVoCyWRu/k6P4QWjtX/U6q72L6l22yZJ7D7YZOA4VKLP/JynM9CUVfrP3EG8IbG8zibeYsQn4ocIa66p9ReRu8ADjmzbbSFCKW+W01q006HE1MvmeEhvO18Z9Dwow6fvf2yrzLid5stKMcukY=

